version: "3"

services: 
  
  home: 
    build: ./home
    restart: always

  pwa-tools:
    build: ./pwa-tools
    restart: always

  assets:
    build: ./assets
    restart: always
  
  js-lib:
    build: ./js-lib
    restart: always

  static-pages:
    build: ./static-pages
    restart: always

  gitlab-slackbot:
    build: ./gitlab-slackbot
    restart: always

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging: 
      options: 
        max-size: 50m
