version: "3"

services:

  # Static Pages

  home:
    image: comameito/static-server
    volumes:
      - ./home:/files:ro
    restart: always

  slides:
    image: comameito/index-server
    volumes:
      - ./slides:/files:ro
    restart: always

  # Shortlink

  shortlink:
    build: ./shortlink
    restart: always


  # MongoDB

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db


  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: 50m
