version: "3"

services: 
  
  home: 
    image: comameito/static-server
    volumes:
      - ./home:/files:ro
    restart: always

  pwa-tools:
    image: comameito/static-server
    volumes:
      - ./pwa-tools:/files:ro
    restart: always

  assets:
    image: comameito/static-server
    volumes:
      - ./assets:/files:ro
    restart: always
  
  js-lib:
    image: comameito/static-server
    volumes:
      - ./js-lib:/files:ro
    restart: always

  static-pages:
    image: comameito/static-server
    volumes:
      - ./static-pages:/files:ro
    restart: always

  gitlab-slackbot:
    build: ./gitlab-slackbot
    restart: always

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging: 
      options: 
        max-size: 50m
